"""Migracion inicial de la base de datos

Revision ID: d8cbde8f8040
Revises: 
Create Date: 2025-09-24 12:01:43.084154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cbde8f8040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dptos',
    sa.Column('id_dpto', sa.Integer(), nullable=False),
    sa.Column('nombre_dpto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_dpto'),
    sa.UniqueConstraint('nombre_dpto')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_control',
    sa.Column('id_control', sa.Integer(), nullable=False),
    sa.Column('nombre_control', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_control'),
    sa.UniqueConstraint('nombre_control')
    )
    op.create_table('tipos_persona',
    sa.Column('id_tipopersona', sa.Integer(), nullable=False),
    sa.Column('nombre_tipopersona', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipopersona'),
    sa.UniqueConstraint('nombre_tipopersona')
    )
    op.create_table('personas',
    sa.Column('id_persona', sa.String(length=20), nullable=False),
    sa.Column('nombre_persona', sa.String(length=150), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('tipo_persona_id', sa.Integer(), nullable=False),
    sa.Column('dpto_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['tipo_control.id_control'], ),
    sa.ForeignKeyConstraint(['dpto_id'], ['dptos.id_dpto'], ),
    sa.ForeignKeyConstraint(['tipo_persona_id'], ['tipos_persona.id_tipopersona'], ),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('registros',
    sa.Column('id_registro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora_registro', sa.DateTime(), nullable=False),
    sa.Column('persona_id', sa.String(length=20), nullable=False),
    sa.Column('tipo_control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['tipo_control_id'], ['tipo_control.id_control'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('usuario')
    op.drop_table('personas')
    op.drop_table('tipos_persona')
    op.drop_table('tipo_control')
    op.drop_table('rol')
    op.drop_table('dptos')
    # ### end Alembic commands ###
